### ISSUE TITLE
[Instil] Support for Scala 3.0

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-java-agent#219]
Update NR's Java Agent instrumentation to support Scala 3.0, introduce appropriate supporting tests for 2.13.5 and clean up the code to remove legacy Scala support (eg: 2.9) that will be deprecated with the upcoming Java 7 EOL.

- [x] Add instrumentation for Scala 3.0
- [x] Update test suite
- [x] Remove deprecated code for Scala 2.9 and earlier

Aha! Link: https://newrelic.aha.io/features/JAVA-257

**Comment by kford-newrelic** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6971089650384575915)

Will be included in the next (7.1) agent release

**Comment by kford-newrelic** [comment]
Implemented as part of the 7.1 release.
