### ISSUE TITLE
Java 7 EOL Notifications

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-java-agent#220]
We intend to EOL support for Java 7 in an upcoming release.

As part of our 6.5.0 Java agent release, will want to indicate in our Release Notes that this is the last release with support for Java 7, and update our docs that as of this 6.5.0 release that Java 7 support is now deprecated.

- [x] Internal stakeholder approval
- [x] Internal communications on Slack
- [x] Internal communications on blog
- [x] Internal communications on "What's New"
- [x] External communications on Explorers Hub

Aha! Link: https://newrelic.aha.io/features/JAVA-256

**Comment by jodeev** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6951060900362934886)

This is primarily a coordination and communication event.

**Comment by jodeev** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6955822611628525372)

Notifications will be done in coordination with the company-wide bulk EOL announcements

**Comment by kford-newrelic** [comment]
Discussed and agreed that this notification would be included as part of the bulk "Q1" EOL notifications.

No special direct notifications needed to current Java 7 customers, since ending support in future releases won't impact those still running older releases.

**Comment by jodeev** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6956663877119099102)

Met with our BusOps and ProdOps partners. Their current coordinated plans are to publish these communications during the week of 5/3. We've provided our draft verbiage and reviewed updates.

**Comment by kford-newrelic** [comment]
Completed. All notifications sent.
