### ISSUE TITLE
JFR Flamegraph GA

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-java-agent#287]
Enable our customers to gain the most out of our JFR (Realtime Java Profiling) feature by enabling it by default in new Java agent releases.

- [x] Complete additional customer scenario testing
- [x] Modify agent configuration files
- [x] Update documentation
- [x] Notify internal stakeholders (support, etc)

Also requires completion of 

- https://github.com/newrelic/newrelic-jfr-core/issues/149
- https://github.com/newrelic/newrelic-jfr-core/issues/171
- https://github.com/newrelic/newrelic-jfr-core/issues/181

Aha! Link: https://newrelic.aha.io/features/JAVA-280

**Comment by kford-newrelic** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6965892383656242699)

Per discussion w/ [@Ramon Guiu](https://newrelic.aha.io/users/6392145647121121434) and [@Ben Evans](https://newrelic.aha.io/users/6680565069540014829) , the next (7.0) agent release will focus on getting the Flamegraph feature to GA, with appropriate posts/documentation updates to promote this to customers but they will have to enable JFR themselves.

In the next (7.1) agent release, we will configure JFR to be on by default.

This approach will give time for these new features to settle in and for us to get customer feedback.

**Comment by kford-newrelic** [comment]
Completed in July in preparation for supporting JFR enablement by default
