### ISSUE TITLE
Switch JDK 18-ea to GA once 18 JDK GA Releases for all appropriate usages

### ISSUE THREAD

**Issue by tbradellis** [newrelic/newrelic-java-agent#669]
The agent will be testing against early access builds.  Once the GA releases, we need to update all references that pull the ea binaries to pull the GA version.

- [x] Update JDK on Jenkins
- [x] Update JDK on GHA builds
- [x] Update the Version Test
- [x] UPdate JavaVersionUtils 

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
Must Have When

**Comment by kford-newrelic** [comment]
Bumped from the planned `7.6.0` release but will be included in the next planned release.

**Comment by tbradellis** [comment]
Once PRs are merged this can be moved to done and closed.
