### ISSUE TITLE
Implement LiC instrumentation for JBoss Logging

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#749]
Write instrumentation for JBoss Logging. I'm not sure if this is actually needed but JBoss has their [own logger](https://github.com/jboss-logging).

This instrumentation still needs the following:
- [ ] Create log level metrics
- [ ] Create LogEvents
- [ ] Create a supportability metric indicating that the module loaded: `Supportability/Logging/enabled/Java/JBossLogger`
- [ ] Append agent metadata to log messages
- [ ] Instrumentation tests

(Replicate to Jira)

**Comment by kford-newrelic** [comment]
Not selected for the agent roadmap.

**Comment by kford-newrelic** [comment]
Dupe of [NR-59596](https://issues.newrelic.com/browse/NR-59596)
